---
title: "zoocat"
output: md_document
variant: markdown_github
---



For using \code{zoocat} package, first load it:

```{r, message=FALSE, highlight=TRUE}
library(zoocat)
```


# Construct a \code{zoocat} object

```{r, highlight=TRUE}
mat <- matrix(round(rnorm(24), 2), ncol = 4)
ctable <- data.frame(treatment = factor(rep(c('a', 'b'), 2), levels = c('a', 'b')), 
                     site = factor(rep(c('s1', 's2'), each = 2), levels = c('s1', 's2')))
zc <- zoocat(mat, order.by = 2011 : 2014, colattr = ctable, index.name = 'year')
print(zc)
```

# Set and get the \code{cattr} table

```{r, highlight=TRUE}
cattr(zc)
zc2 <- zc
cattr(zc2) <- data.frame(cattr(zc), observer = 'Jack')
print(zc2)
```


# Merge by columns

```{r, highlight=TRUE}
zc2 <- zc + 10
cattr(zc2) <- data.frame(site = 's3', added = rep(TRUE, 4))
zc.merge <- cbind(zc, zc2)
cattr(zc.merge)
```


# Melt and cast

```{r, highlight=TRUE}
df.melt <- melt(zc)
head(df.melt)
```


```{r, highlight=TRUE}
cast2zoocat(df.melt, index.var = 'year', value.var = 'value')
```


# Reset the index variable

```{r, highlight=TRUE}
reset_index_var(zc, index.var = 'treatment')
```

